
# Site settings
title: TTLequals0
title_image: ./assets/IMG_7718.PNG
email: dkrachtus@ttlequals0.com
title_description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TTLequals0.com" # the base hostname & protocol for your site
addthis_id: ra-570ae5c51aa52c0e
disqus_account: ttlequals0
post_limit: 5

# Social usernames/URLs
twitter_username: TTLequals0
github_username:  TTLequals0
instagram_username:  TTLequals0
linkedin_link: https://www.linkedin.com/in/ttlequals0

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
